global:
  scrape_interval: 10s

# Option A: Prometheus to scrape metrics from Otel
# scrape_configs:
#   - job_name: 'otel-collector'
#     scrape_interval: 10s
#     static_configs:
#       - targets: ['otel-collector:9090']
